---
# tasks file for codedeploy
- name: Install boto library
  pip:
    name: boto
    state: present
  
- name: Installs and starts the AWS CodeDeploy Agent
  aws_codedeploy:
    enabled: yes

- name: Start AWS CodeDeploy agent
  service:
    name: codedeploy-agent
    state: started
    enabled: yes
  become: yes
